#!/usr/bin/env bash

iDIR="$HOME/.config/HyprV/mako/icons"

# Get brightness
get_backlight() {
	LIGHT=$(printf "%.0f\n" $(brightnessctl i))
	echo "${LIGHT}%"
}

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "12490") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "12490") && ("$current" -le "24980") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "24980") && ("$current" -le "37470") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "37470") && ("$current" -le "49960") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "49960") && ("$current" -le "62450" || "$current" -le "62451") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness: $(brightnessctl -m i | cut -d, -f4)"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- && get_icon && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi